name: Upload to S3

on:
  release:
    types: [published]

env:
  S3_BUCKET_URL: ${{ vars.S3_BUCKET_URL }}

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Upload JSON files to S3
        run: |
          set -e
          exit_code=0
          for file in $(find . -name "*.json"); do
            if ! aws s3 cp "$file" "${{ env.S3_BUCKET_URL }}/${file#./}"; then
              echo "Failed to upload $file"
              exit 1
            fi
          done 